config/routes.rb
Derdiedas::Application.routes.draw do

  get "home/index"

  resources :words
  resources :users
  resources :sessions, :only => [:new, :create, :destroy]
  match 'nouns/:id/check' => 'home#check', :as => :check

  match '/signup', :to => 'users#new'
  match '/signin', :to => 'sessions#new'
  match '/signout', :to => 'sessions#destroy', :via => :delete

  root :to => 'home#index'

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    if signed_in?
      sample_size = Word.count / 10
      sample_size = 1 if sample_size < 1
      words = prio_list.slice(0, sample_size)
    else
      words = Word.all
    end
    @word = words.shuffle.first
  end
  def check
    @word = Word.find(params[:id])
    if given_answer == @word.article
      flash_data = { :success=> "Sehr gut! #{@word.to_s} war richtig"}
    else
      flash_data = { :error=> "mmmm Eigentlich war #{@word.to_error_s} richtig"}
    end
    save_guess if signed_in?
    redirect_to root_url, :flash => flash_data
  end
  private

    def given_answer
      answer = nil
      %w(der die das).each do |article|
        answer = article if params["chose_#{article}"]
      end
      answer
    end
    def save_guess
      guess = current_user.guesses.build(word_id: @word.id, answer: given_answer)
      guess.save
    end

end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/index.html.erb
<% unless signed_in? %>
  <p> 
  <%= link_to "Sign up!", signup_path, class: "btn btn-medium " %>
  <strong>
    to track your progress!
  </strong>
  </p>
<% end %>

<div class="hero-unit span10">  

  <div class="row">
    <div class="span8 offset1 pagination-centered">

      <div class="well">
        <h1> <%=@word.noun%> </h1>
      </div>


    </div>
  </div>


  <div class="row">
    <%= form_for(@word, :url => check_url(:id => @word.id)) do %>
      <% # send the clicked one to the home/check action, see match route %>
      <div class="span2 offset2">
        <p>
        <%= submit_tag "Der", name: "chose_der",class: "btn btn-large btn-inverse btn-block" %>
        </p>
      </div>
      <div class="span2 offset0">
        <p>
        <%= submit_tag "Die", name: "chose_die",class: "btn btn-large btn-danger btn-block" %>
        </p>
      </div>
      <div class="span2 offset0">
        <p>
        <%= submit_tag "Das", name: "chose_das",class: "btn btn-large btn-warning btn-block" %>
        </p>
      </div>
    <% end %>
  </div>

  <div class="row">
    <small>
      <div class="span8 offset1">
        <br>
        <p> 
        Frequency of <em><%=@word.noun%></em> :  <strong> <%=@word.weight%> </strong> 
        (10 most frequent, 1 uncommon)
        </p>
        <% if signed_in? %>
          <p> 
          Your level for <em><%=@word.noun%></em>: <strong> <%=current_user.word_level(@word)%> </strong>   
          (10 worst level, 1 you got it!)
          </p>
        <% end %>
        <p> 
        <em><%=@word.noun%></em> :  <%=@word.definitions%> 
        </p>
      </div>
    </small>
  </div>

  <div class="row">
    <big>
      <div class="span8 offset1">
        <% flash.each do |key, value| %>
          <div class="alert fade in alert-<%= key %>">
            <%= value %>
            <a href="#" data-dismiss="alert" class="close">&times</a>
          </div>
        <% end %>
      </div>
    </big>
  </div>

</div>