config/routes.rb
Derdiedas::Application.routes.draw do

  get "home/index"

  resources :words
  resources :users
  resources :sessions, :only => [:new, :create, :destroy]
  match 'nouns/:id/check' => 'home#check', :as => :check

  match '/signup', :to => 'users#new'
  match '/signin', :to => 'sessions#new'
  match '/signout', :to => 'sessions#destroy', :via => :delete

  root :to => 'home#index'

end

app/models/word.rb
# == Schema Information
#
# Table name: words
#
#  id         :integer          not null, primary key
#  noun       :string(255)
#  article    :string(255)
#  weight     :integer
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Word < ActiveRecord::Base
  attr_accessible :article, :noun, :weight, :definitions
  validates :noun, :presence => true
  #validates :definitions, :presence => true
  validates :weight, :numericality => { :only_integer => true }
  validates :article, :inclusion => { :in => %w(der die das),
    :message => "%{value} is not a valid german article" }

  has_many :guesses
  has_many :users, :through => :guesses

  def to_s
    self.article.to_s.capitalize + " " + self.noun.to_s
  end
  def to_error_s
    self.article.to_s.downcase + " " + self.noun.to_s
  end

end

app/controllers/words_controller.rb
class WordsController < ApplicationController
  # GET /words
  # GET /words.json
  def index
    @words = prio_list
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @words }
    end
  end

  # GET /words/1
  # GET /words/1.json
  def show
    @word = Word.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @word }
    end
  end

  # GET /words/new
  # GET /words/new.json
  def new
    @word = Word.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @word }
    end
  end

  # GET /words/1/edit
  def edit
    @word = Word.find(params[:id])
  end

  # POST /words
  # POST /words.json
  def create
    @word = Word.new(params[:word])

    respond_to do |format|
      if @word.save
        format.html { redirect_to @word, notice: 'Word was successfully created.' }
        format.json { render json: @word, status: :created, location: @word }
      else
        format.html { render action: "new" }
        format.json { render json: @word.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /words/1
  # PUT /words/1.json
  def update
    @word = Word.find(params[:id])

    respond_to do |format|
      if @word.update_attributes(params[:word])
        format.html { redirect_to @word, notice: 'Word was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @word.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /words/1
  # DELETE /words/1.json
  def destroy
    @word = Word.find(params[:id])
    @word.destroy

    respond_to do |format|
      format.html { redirect_to words_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/words_helper.rb
module WordsHelper
end

app/views/words/_form.html.erb
<%= form_for(@word) do |f| %>
  <% if @word.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@word.errors.count, "error") %> prohibited this word from being saved:</h2>

      <ul>
      <% @word.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :noun %><br />
    <%= f.text_field :noun %>
  </div>
  <div class="field">
    <%= f.label :article %><br />
    <%= f.text_field :article %>
  </div>
  <div class="field">
    <%= f.label :weight %><br />
    <%= f.number_field :weight %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/words/edit.html.erb
<h1>Editing word</h1>

<%= render 'form' %>

<%= link_to 'Show', @word %> |
<%= link_to 'Back', words_path %>

app/views/words/index.html.erb
<h1>Training Words</h1>
<table class="table-stripped table">
  <tr>
    <th>Article</th>
    <th>Noun</th>
    <th>Weight</th>
    <% if signed_in? %>
    <th>Level</th>
    <th>Prob</th>
    <% end %>
    <th>Definitions</th>
  </tr>
<% @words.each do |word| %>
  <tr>
    <td><%= word.article %></td>
    <td><%= word.noun %></td>
    <td><%= word.weight %></td>
    <% if signed_in? %>
    <td><%= current_user.word_level(word) %></td>
    <td><%= current_user.word_prob(word) %></td>
    <% end %>
    <td><%= word.definitions %></td>
  </tr>
<% end %>
</table>
<br />

app/views/words/new.html.erb
<h1>New word</h1>

<%= render 'form' %>

<%= link_to 'Back', words_path %>

app/views/words/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Noun:</b>
  <%= @word.noun %>
</p>

<p>
  <b>Article:</b>
  <%= @word.article %>
</p>

<p>
  <b>Weight:</b>
  <%= @word.weight %>
</p>


<%= link_to 'Edit', edit_word_path(@word) %> |
<%= link_to 'Back', words_path %>