config/routes.rb
Derdiedas::Application.routes.draw do

  get "home/index"

  resources :words
  resources :users
  resources :sessions, :only => [:new, :create, :destroy]
  match 'nouns/:id/check' => 'home#check', :as => :check

  match '/signup', :to => 'users#new'
  match '/signin', :to => 'sessions#new'
  match '/signout', :to => 'sessions#destroy', :via => :delete

  root :to => 'home#index'

end

app/views/layouts/_footer.html.erb
<footer class="footer">
<ul class="nav pull-right">
  <!--
  <li><%= link_to "About",   '#' %></li>
  <li><%= link_to "Contact", '#' %></li>
  -->
  <% unless signed_in? %>
  <li>
          <%= link_to "Sign up!", signup_path, class: "btn btn-large btn-primary" %>
          <p> 
          <strong>
          ...and track your progress!
          </strong>
          </p>
  </li>
  <% end %>
</ul>
<ul class="nav pull-left">
  <li>
  <small>
  All data extracted from <%= link_to "Wiktionary",   'http://de.wiktionary.org/wiki/Wiktionary:Hauptseite' %>, and available under the <%= link_to " Creative Commons Attribution/Share-Alike License",   'http://creativecommons.org/licenses/by-sa/3.0/' %>
  </small>
  </li>
</ul>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
<div class="navbar-inner">
  <div class="container">
    <%= link_to "Der? Die? Das? Nur eins ist richtig!  [BETA]", root_path, id: "logo" %>
    <nav>
    <ul class="nav pull-right">
      <li><%= link_to "Home", root_path %></li>
        <li><%= link_to "Words", words_path %></li>

      <% if signed_in? %>
        <li><%= link_to "Users", users_path %></li>
        <li id="fat-menu" class="dropdown">
        <a href="#" class="dropdown-toggle" data-toggle="dropdown"> Account <b class="caret"></b></a>
        <ul class="dropdown-menu">
          <li><%= link_to "Profile", current_user %></li>
          <li><%= link_to "Settings", edit_user_path(current_user) %></li>
          <li class="divider"></li>
          <li>
          <%= link_to "Sign out", signout_path, method: "delete" %>
          </li>
        </ul>
        </li>
      <% else %>
        <li><%= link_to "Sign in", signin_path %></li>
      <% end %>

    </ul>
    </nav>
  </div>
</div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= yield(:title)%></title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
   <%= render 'layouts/shim' %>
</head>
<body>


   <%= render 'layouts/header' %>
  <div class="container">
   <%= yield %>
   <%= render 'layouts/footer' %>
   <%= debug(params) if Rails.env.development? %>
  </div>

</body>
</html>